var einwohnerEu = 447;
var prozent = 100;
var italien = -1;
var einwohnerDe = 83.2;
var einwohnerIt = 59.26;
var einwohnerFr = 67.44;
var einwohnerSp = 47.39;
var einwohnerDeW = 80.3;
var einwohnerItW = 59.96;
var einwohnerFrW = 63.07;
var einwohnerSpW = 46.74;
var deProzent = einwohnerDe / einwohnerEu * prozent;
var itProzent = einwohnerIt / einwohnerEu * prozent;
var frProzent = einwohnerFr / einwohnerEu * prozent;
var spProzent = einwohnerSp / einwohnerEu * prozent;
var deDazu = einwohnerDe / einwohnerDeW * prozent - prozent;
var itDazu = (einwohnerIt / einwohnerItW * prozent - prozent) * italien;
var frDazu = einwohnerFr / einwohnerFrW * prozent - prozent;
var spDazu = einwohnerSp / einwohnerSpW * prozent - prozent;
var deDazuN = einwohnerDe - einwohnerDeW;
var itDazuN = (einwohnerIt - einwohnerItW) * italien;
var frDazuN = einwohnerFr - einwohnerFrW;
var spDazuN = einwohnerSp - einwohnerSpW;
console.log("Deutschland hat " + einwohnerDe + " Mio. Einwohner.");
console.log("Italien hat " + einwohnerIt + " Mio. Einwohner.");
console.log("Frankreich hat " + einwohnerFr + " Mio. Einwohner.");
console.log("Spanien hat " + einwohnerSp + " Mio. Einwohner.");
console.log("In Deutschland wohnen " + deProzent + "% der Einwohner der EU.");
console.log("In Italien wohnen " + itProzent + "% der Einwohner der EU.");
console.log("In Frankreich wohnen " + frProzent + "% der Einwohner der EU.");
console.log("In Spanien wohnen " + spProzent + "% der Einwohner der EU.");
console.log("Deutschland ist seit 2011 um " + deDazu + "% gewachsen.");
console.log("Italien ist seit 2011 um " + itDazu + "% geschrumpft.");
console.log("Frankreich ist seit 2011 um " + frDazu + "% gewachsen.");
console.log("Spanien ist seit 2011 um " + spDazu + "% gewachsen.");
console.log("Deutschland hat seit 2011 " + deDazuN + " Mio. Einwohner dazugewonnen.");
console.log("Italien hat seit 2011 " + itDazuN + " Mio. Einwohner verloren.");
console.log("Frankreich hat seit 2011 " + frDazuN + " Mio. Einwohner dazugewonnen.");
console.log("Spanien hat seit 2011 " + spDazuN + " Mio. Einwohner dazugewonnen.");
//# sourceMappingURL=script.js.map